[package]
name = "day1"
version = "0.1.0"
authors = ["Hung Nguyen <hungnq1989@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
